owner = "login"
repositoryName = "arepository"

# "rules" allow to close issues
[[rules]]
  # search issues with those labels (AND)
  includedLabels = ["label01", "label02"]
  # exclude issues with those labels (AND)
  excludedLabels = ["label03"]
  message = """\
I'll close the issue due to inactivity but feel free to re-open if needed.
  """
  # number of days since the issue creation
  daysSinceCreation = 360
  # number of days since the last issue update
  daysSinceUpdate = 180

[[rules]]
  includedLabels = ["label04"]
  excludedLabels = []
  message = """\
I'll close the issue due to inactivity but feel free to re-open if needed.
  """
  daysSinceCreation = 90
  daysSinceUpdate = 90

[[rules]]
  # Disable a rule
  disable = true
  includedLabels = ["label05"]
  excludedLabels = []
  message = """\
I'll close the issue due to inactivity but feel free to re-open if needed.
  """
  daysSinceCreation = 90
  daysSinceUpdate = 90

# "locks" allow to lock issues
[[locks]]
  # number of days since the last issue update
  daysSinceUpdate = 90
  # exclude issues with those labels (AND)
  excludedLabels = ["label8"]
  # label to add on the issue (can be empty)
  label = "label7"
  # Disable a rule
  disable = false
